const languages = {
  eng: {
    Undo: "Undo",
    Redo: "Redo",
    Clear: "Clear",
    Horizontalflip: "Horizontal flip",
    Verticalflip: "Vertical flip",
    Changemode: "Change mode",
    Group: "Group",
    Ungroup: "Ungroup",
    SelectAll: "Select All",
    Controls: "Controls",
    Text: "Text",
    Export: "Export",
    Assets: "Assets",
    FontFace: "Font Face",
    SelectFont: "Select Font",
    AddToCanvas: "Add To Canvas",
    AddToPath: "Add To Path",
    Effects: "Effects",
    SelectFormat: "Select Format",
    Grayscale: "Grayscale",
    Avg: "Avg.",
    Lum: "Lum.",
    Light: "Light.",
    Invert: "Invert",
    Colormatrixfilters: "Colormatrix filters",
    Sepia: "Sepia",
    BlackWhite: "Black/White",
    Brownie: "Brownie",
    Vintage: "Vintage",
    Kodachrome: "Kodachrome",
    Technicolor: "Technicolor",
    Polaroid: "Polaroid",
    Removecolor: "Remove color",
    Color: "Color",
    Distance: "Distance",
    Brightness: "Brightness",
    Gamma: "Gamma",
    Red: "Red",
    Green: "Green",
    Blue: "Blue",
    Contrast: "Contrast",
    Saturation: "Saturation",
    Hue: "Hue",
    Noise: "Noise",
    Pixelate: "Pixelate",
    Blur: "Blur",
    Sharpen: "Sharpen",
    Emboss: "Emboss",
    BlendColor: "Blend Color",
    Mode: "Mode",
    Alpha: "Alpha",
    BlendImage: "Blend Image",
    Dropfileshere: "Drop files here",
    Pleasechooseorfropfiles: "Please choose or drop files"
  }
}

export default languages;

